# NB: this file was automatically generated by Dynare
#     from NKV_EA_est.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(12, 26);
gp = zeros(12, 24, 26);
end
return (rp, gp)
end
