# NB: this file was automatically generated by Dynare
#     from NKV_EA_est.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(12, 26);
gp = zeros(12, 12, 26);
end
return (rp, gp)
end
