# NB: this file was automatically generated by Dynare
#     from NKV_EA_est.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[1]=0;
    ys_[2]=0;
    ys_[3]=0;
    ys_[4]=0;
    ys_[5]=0;
    ys_[6]=(params[26]-1)*100;
    ys_[7]=0;
    ys_[8]=0;
    ys_[9]=params[14];
    ys_[10]=(params[25]-1)*400;
    # Auxiliary equations
ys_[11]=ys_[3];
ys_[12]=ys_[11];
end
end
